### ISSUE TITLE
Rename this repository and add others for builddeps

### ISSUE THREAD

**Issue by bryanwweber** [Cantera/conda-recipes#6]
Should we rename this repository to be `cantera-recipe` and add repos for `3to2-recipe`, `scons-recipe`, `sphincontrib-doxylink-recipe`, and `sphinxcontrib-matlabdomain-recipe`, a la conda-forge?

**Comment by speth** [comment]
How much do we really want to be maintaining other conda recipes? We need a SCons recipe only because Anaconda has an out-of-date version. The sphinxcontrib recipes are only needed if you're building the documentation, which isn't done as part of the conda build process. I don't think 3to2 is an active project, so there shouldn't be a need to update it (and it eventually just goes away when we drop support for Python 2.7).

**Comment by bryanwweber** [comment]
OK I agree with all of that!
